/*
 * blanco Framework
 * Copyright (C) 2004-2006 IGA Tosiki
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 */
package blanco.db.expander.common;

import blanco.cg.BlancoCgObjectFactory;
import blanco.cg.valueobject.BlancoCgClass;
import blanco.cg.valueobject.BlancoCgField;
import blanco.cg.valueobject.BlancoCgMethod;
import blanco.cg.valueobject.BlancoCgSourceFile;

import java.util.List;

/**
 * AbstractDbConnection に関するクラス
 * 
 * このクラスが生成するクラスはblancoDbPhpが生成したソースコードで利用されます
 * 
 * @author Junji Amano
 */
public class AbstractDbConnectionClassPhp {
    /**
     * クラス名
     */
    public static final String CLASS_NAME = "AbstractDbConnection";

    /**
     * blancoCg オブジェクトファクトリ。
     */
    private BlancoCgObjectFactory fCgFactory = null;

    /**
     * このクラスが含まれるソースコード。
     */
    private BlancoCgSourceFile fCgSourceFile = null;

    public AbstractDbConnectionClassPhp(final BlancoCgObjectFactory cgFactory,
                                        final String argPackage) {
        fCgFactory = cgFactory;
        fCgSourceFile = fCgFactory.createSourceFile(argPackage,
                "This code is generated by blanco Framework.");
    }

    public BlancoCgSourceFile expand() {
        final BlancoCgClass cgClass = fCgFactory.createClass(CLASS_NAME, null);
        cgClass.setAbstract(true);
        fCgSourceFile.getClassList().add(cgClass);

//        cgClass.getExtendClassList().add(
//                fCgFactory.createType("PDOException"));

        {
            final List listDesc = cgClass.getLangDoc().getDescriptionList();

            listDesc.add("AbstractDbConnection クラス");
            listDesc.add("このクラスはblancoDbが生成したソースコードで利用されます 。");
            listDesc.add("※このクラスは、ソースコード自動生成後のファイルとして利用されます。");
            listDesc.add("");
            listDesc.add("@author blanco Framework");
        }

        {
            final BlancoCgMethod cgMethod = fCgFactory.createMethod("getConnection",
                    "getConnection メソッド");
            cgClass.getMethodList().add(cgMethod);

            cgMethod.setAbstract(true);
            cgMethod.getParameterList().add(
                    fCgFactory.createParameter("boolAlternativeConnectionFlg", "boolean", ""));

        }

        // required 文を出力しない ... 将来的には xls で指定するように？
        fCgSourceFile.setIsImport(false);

        return fCgSourceFile;
    }
}